services:
  - type: web
    name: rapido-flash-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL_1
        sync: false
      - key: FRONTEND_URL_2
        sync: false
      - key: FRONTEND_URL_3
        sync: false
      - key: FRONTEND_URL_4
        sync: false
      - key: KKIAPAY_PRIVATE_KEY
        sync: false
      - key: KKIAPAY_SECRET
        sync: false
