import React, { createContext, useState, useEffect, useCallback, useMemo } from 'react';
import { pickLocalized, pickProductDisplayName } from '../utils/i18nContent';

const STORAGE_KEY = 'rapido_lang';

export const translations = {
  fr: {
      nav: {
      home: 'Accueil',
      cart: 'Panier',
      orders: 'Commandes',
      invoices: 'Factures',
      settings: 'Paramètres',
      logout: 'Déconnexion',
    },
    navbar: {
      chooseAddress: 'Choisir une adresse',
      modify: 'Modifier',
      searchPlaceholder: 'Rechercher un produit, une boutique...',
      userMenu: 'Menu utilisateur',
      sectionCategories: 'Catégories',
      sectionStructures: 'Structures',
      sectionProducts: 'Produits',
      changeDeliveryAddress: "Modifier l'adresse de livraison",
      changeLanguage: 'Changer la langue',
      language: 'Langue',
    },
    home: {
      deliveryTo: 'Livraison à',
      selectAddress: 'Sélectionner une adresse',
      searchPlaceholder: 'Rechercher un produit, une boutique...',
      productSearchTitle: 'Produits trouvés',
      productSearchLoading: 'Recherche en cours…',
      productSearchEmpty: 'Aucun produit ne correspond. Voici des structures à explorer.',
      openShop: 'Voir la boutique',
      addToCartShort: 'Panier',
      distanceKm: 'km',
      categories: 'Catégories',
      all: 'Tous',
      noStructuresFound: 'Aucune structure trouvée',
      call: 'Appeler',
      whatsapp: 'WhatsApp',
      min: 'min',
      discoverStructures: 'Découvrir les structures',
      previous: 'Précédent',
      next: 'Suivant',
      freeDeliveryCotonou: 'La livraison est gratuite à Cotonou. Profitez-en pour commander vos produits préférés !',
      gotIt: "J'ai compris",
      hideBannerToday: 'Masquer pour 24 h',
      allProductsTitle: 'Tous les produits',
      allProductsEmpty: 'Aucun produit disponible pour cette catégorie.',
      shopByCategory: 'Parcourir par catégorie',
      railSwipeHint: 'Faites défiler pour voir plus',
      productsListed: 'produits',
      noProductsPreview: 'Découvrir la carte',
      promoOff: 'promo',
      promoFreeDelivery: 'Livraison gratuite',
      promoBadgesAria: 'Offres promotionnelles sur ce produit',
    },
    settings: {
      title: 'Paramètres',
      profilePhoto: 'Photo de profil',
      changePhoto: 'Changer la photo',
      uploading: 'Upload en cours...',
      personalInfo: 'Informations personnelles',
      name: 'Nom',
      email: 'Email',
      phone: 'Téléphone',
      notSet: 'Non défini',
      editInfo: 'Modifier les informations',
      deliveryAddress: 'Adresse de livraison',
      noAddressDefined: 'Aucune adresse de livraison définie',
      modifyAddress: "Modifier l'adresse",
      setAddress: 'Définir une adresse',
      security: 'Sécurité',
      changePassword: 'Changer le mot de passe',
      currentPassword: 'Mot de passe actuel',
      newPassword: 'Nouveau mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      cancel: 'Annuler',
      save: 'Enregistrer',
      saving: 'Enregistrement...',
      logout: 'Se déconnecter',
      yourName: 'Votre nom',
      yourEmail: 'Votre email',
      yourPhone: 'Votre numéro de téléphone',
      photoUpdated: 'Photo mise à jour avec succès !',
      infoUpdated: 'Informations mises à jour avec succès !',
      comingSoon: 'Fonctionnalité à venir',
      info: 'Information',
      invalidFormat: 'Format invalide',
      selectImage: 'Veuillez sélectionner un fichier image',
      fileTooBig: "L'image ne doit pas dépasser 500 Mo",
      uploadError: "Erreur lors de l'upload de la photo",
      updateError: 'Erreur lors de la mise à jour',
      error: 'Erreur',
    },
    invoices: {
      title: 'Mes factures / reçus',
      subtitle: 'Reçus de paiement en ligne (Kkiapay)',
      empty: 'Aucune facture numérique pour le moment.',
      viewReceipt: 'Voir le reçu',
      downloadReceipt: 'Télécharger PDF',
      expired: 'Expiré',
    },
    maintenance: {
      title: 'On revient tout de suite',
      subtitle: 'Le site est en maintenance',
      defaultMessage:
        'Nous améliorons Rapido Flash pour vous offrir une meilleure expérience. Merci de votre patience — à très vite !',
      staffLogin: 'Connexion espace pro (tableau de bord)',
      dashboardTitle: 'Maintenance du site',
      dashboardHint:
        'Lorsque la maintenance est activée, les clients voient une page d’attente. Vous gardez l’accès au tableau de bord.',
      toggleLabel: 'Mettre le site en maintenance',
      messageLabel: 'Message affiché aux visiteurs',
      messagePlaceholder: 'Ex. : retour prévu dans quelques heures…',
      save: 'Enregistrer',
      saved: 'Paramètres enregistrés',
      loadError: 'Impossible de charger les paramètres',
    },
    receipt: {
      title: 'Reçu de paiement',
      expiredMessage: 'Ce reçu n’est plus valide (30 jours dépassés).',
      print: 'Imprimer',
      download: 'Télécharger PDF',
      pdfError: 'Impossible de générer le PDF. Réessayez ou utilisez « Imprimer ».',
      orderRef: 'Référence commande',
      date: 'Date',
      amount: 'Montant payé',
      client: 'Client',
      structure: 'Structure',
      paidOnline: 'Paiement en ligne confirmé',
    },
    cart: {
      title: 'Panier',
      emptyTitle: 'Votre panier est vide',
      emptySubtitle: 'Ajoutez des produits pour commencer',
      discoverStructures: 'Découvrir les structures',
      subTotal: 'Sous-total',
      deliveryFee: 'Frais de livraison',
      total: 'Total',
      checkout: 'Passer la commande',
      freeDeliveryPromoNote: 'Livraison offerte (promo produit)',
    },
    locationEditor: {
      title: "Modifier l'adresse de livraison",
      instructionLabel: 'Indications pour le livreur (obligatoire)',
      instructionPlaceholder: 'Ex. : code portail, étage, repères…',
      telephoneLabel: 'Numéro à appeler pour la livraison (obligatoire)',
      telephonePlaceholder: 'Ex. : +229 …',
      searchPlaceholder: 'Rechercher une adresse...',
      useMyLocation: 'Utiliser ma position',
      selectedAddress: 'Adresse sélectionnée :',
      cancel: 'Annuler',
      save: 'Enregistrer',
      saving: 'Enregistrement...',
      geolocError: 'Impossible de récupérer votre position',
      geolocErrorTitle: 'Erreur de géolocalisation',
      saveError: 'Erreur lors de la sauvegarde',
      hideMap: 'Masquer la carte',
    },
    orders: {
      title: 'Commandes',
      pageTitle: 'Mes commandes',
      loading: 'Chargement de vos commandes…',
      noOrders: 'Aucune commande',
      noOrdersBody: "Vous n'avez pas encore passé de commande.",
      browseProducts: 'Découvrir les boutiques',
      totalLabel: 'Total',
      viewReceipt: 'Voir le reçu / facture',
      followOrder: 'Suivre ma commande',
      followOrderAria: 'Suivre ma commande',
      statusPending: 'En attente',
      statusConfirmed: 'Confirmée',
      statusPreparing: 'En préparation',
      statusDelivery: 'En livraison',
      statusDelivered: 'Livrée',
      statusCancelled: 'Annulée',
      paymentCash: 'Espèces à la livraison',
      paymentMomoBefore: 'Mobile Money avant livraison',
      paymentMomoAfter: 'Mobile Money après livraison',
      whatsappPaidLine: 'OK - Paiement en ligne (MoMo) : recu',
      whatsappTemplate:
        'Bonjour \u00e9quipe Rapido Flash\n\n' +
        'Je souhaite suivre ma commande pass\u00e9e sur l\u2019application et conna\u00eetre son avancement.\n\n' +
        '--------------------------------\n' +
        'RECAPITULATIF\n' +
        '--------------------------------\n' +
        '- Reference courte : {{ref}}\n' +
        '- ID commande : {{id}}\n' +
        '- Structure : {{shop}}\n' +
        '- Date : {{date}}\n' +
        '- Statut sur l\u2019app : {{status}}\n' +
        '- Sous-total produits : {{subtotal}} FCFA\n' +
        '- Frais de livraison : {{shipping}} FCFA\n' +
        '- Total : {{total}} FCFA\n' +
        '- Mode de paiement : {{payment}}\n' +
        '{{paidExtra}}\n\n' +
        '--------------------------------\n' +
        'LIVRAISON\n' +
        '--------------------------------\n' +
        '- Adresse : {{address}}\n' +
        '- Telephone (livraison) : {{deliveryPhone}}\n' +
        '- Consignes : {{instruction}}\n\n' +
        '--------------------------------\n' +
        'DETAIL DES ARTICLES\n' +
        '--------------------------------\n' +
        '{{items}}\n\n' +
        '--------------------------------\n' +
        'CLIENT\n' +
        '--------------------------------\n' +
        '- Nom : {{clientName}}\n' +
        '- Email : {{clientEmail}}\n' +
        '- Telephone (compte) : {{accountPhone}}\n\n' +
        'Merci de me tenir inform\u00e9(e) de la progression de ma commande.\n\n' +
        'Bien cordialement,\n' +
        '{{clientName}}',
    },
    checkout: {
      title: 'Paiement',
      pay: 'Payer',
      processing: 'Traitement...',
      selectAddress: 'Veuillez sélectionner une adresse de livraison',
      addressRequired: 'Adresse requise',
      paymentSuccess: 'Paiement effectué avec succès !',
      paymentSuccessTitle: 'Paiement réussi',
      paymentCancelled: 'Paiement annulé ou échoué',
      paymentError: 'Erreur lors du paiement. Veuillez réessayer.',
      serviceError: 'Service de paiement non disponible. Veuillez rafraîchir la page et réessayer.',
      orderError: 'Erreur lors de la commande. Veuillez réessayer.',
      paymentMethod: 'Mode de paiement',
      cashOnDelivery: 'Espèces à la livraison',
      cashOnDeliveryHint: 'Vous payez en liquide au livreur.',
      momoBefore: 'Mobile Money avant la livraison',
      momoBeforeHint: 'Paiement en ligne (MoMo) maintenant, puis livraison.',
      momoAfter: 'Mobile Money après la livraison',
      momoAfterHint: 'Commande enregistrée ; vous paierez en MoMo à réception.',
      confirmOrder: 'Confirmer la commande',
      orderCreated: 'Commande enregistrée !',
      telephoneRequired: 'Le numéro pour la livraison est obligatoire (minimum 8 chiffres).',
      instructionRequired: 'Les indications pour le livreur sont obligatoires (code portail, étage, repères, etc.).',
      openMapToChoose: 'Afficher la carte pour choisir le point exact',
      deliveryAddressTitle: 'Adresse de livraison',
      backToCart: 'Retour',
      finalizeTitle: 'Finaliser la commande',
      recapTitle: 'Récapitulatif',
      selectedAddressLabel: 'Adresse',
      useCurrentLocation: 'Utiliser ma position actuelle',
      chooseOnMap: 'Choisir sur la carte',
      paymentStepTitle: 'Mode de paiement',
      paymentStepSubtitle: 'Choisissez comment vous souhaitez payer',
      continueToDelivery: 'Continuer vers la livraison',
      addressModalTitle: 'Adresse de livraison',
      addressModalSubtitle: 'Recherchez une adresse ou utilisez votre position pour la géolocaliser.',
      confirmAndOrder: 'Valider et passer la commande',
      successTitle: 'Merci ! Votre commande est enregistrée',
      successSubtitle: 'Récapitulatif ci-dessous. Suivez votre commande sur WhatsApp ou consultez vos commandes.',
      viewOrders: 'Voir mes commandes',
      backHome: 'Retour à l’accueil',
    },
    common: {
      cancel: 'Annuler',
      save: 'Enregistrer',
      modify: 'Modifier',
      user: 'Utilisateur',
      profile: 'Profil',
      french: 'Français',
      english: 'English',
      error: 'Erreur',
    },
    i18n: {
      nameEn: 'Nom (anglais)',
      nameEnHint: 'Optionnel. Affiché quand la langue du site est « English ».',
      descEn: 'Description (anglais)',
      productNameEn: 'Nom produit (anglais)',
      productDescEn: 'Description (anglais)',
      homeCardNameEn: 'Nom carte d’accueil (anglais)',
      structureNameEn: 'Nom de la structure (anglais)',
      structureDescEn: 'Description (anglais)',
      productCharacteristics: 'Caractéristiques',
      productCharacteristicsHint: 'Une ligne = un point. Affiché dans « Détails du produit » sur la page boutique (fiche produit).',
      productCharacteristicsEn: 'Caractéristiques (anglais)',
      productPromoSection: 'Promotions (cartes & commande)',
      promoFreeShippingLabel: 'Mettre en avant la livraison gratuite : si la commande contient ce produit, les frais de livraison sont offerts.',
      promoPercentLabel: 'Réduction de prix (%)',
      promoPercentHint: 'Entre 1 et 90, ou vide pour désactiver. Le prix payé est calculé automatiquement.',
      productDescriptionFormatHint:
        'Retours à la ligne : utilisez Entrée. Une ligne vide sépare deux paragraphes. Gras : **texte** ou __texte__. Lien : [libellé](https://…) — uniquement des adresses en http ou https.',
      productDescriptionPreview: 'Aperçu (comme sur la fiche produit)',
      productRecommended: 'Produit recommandé',
      productRecommendedHint: 'Badge « Recommandé » sur la fiche produit et les cartes d’accueil (en complément des avis).',
    },
    store: {
      loading: 'Chargement de la structure...',
      notFound: 'Structure non trouvée',
      notFoundDesc: "La structure demandée n'existe pas ou a été supprimée.",
      backHome: "Retour à l'accueil",
      back: 'Retour',
      productSearchPlaceholder: 'Recherche de produits',
      productSearchAria: 'Recherche de produits dans cette boutique',
      orderDaysLabel: 'Jours de commande / vente :',
      orderDayBefore: 'Pensez à commander la veille pour être livré le jour prévu.',
      filterAll: 'Tous',
      filterAllProducts: 'Tous les produits',
      menu: 'Menu',
      cartTitle: 'Chariot',
      contact: 'Contact',
      callTitle: 'Appeler',
      whatsappTitle: 'Contacter par WhatsApp',
      noProducts: 'Aucun produit disponible',
      noProductsStructure: 'Aucun produit pour cette structure.',
      noProductsCategory: 'Aucun produit dans cette catégorie.',
      noProductsCategoryDesktop: 'Aucun produit dans cette catégorie.',
      cartEmpty: 'Ajouter un élément pour commencer',
      total: 'Total',
      viewCart: 'Voir le panier',
      articles: 'article(s)',
      addToCart: 'Ajouter au panier',
      buy: 'Acheter',
      share: 'Partager',
      zoomAlt: 'Vue agrandie',
      close: 'Fermer',
      productPageAria: 'Fiche produit',
      productDefaultEyebrow: 'Produit',
      productGalleryThumbsAria: 'Autres vues du produit',
      zoomHint: 'Cliquez sur la photo pour agrandir.',
      productDetailsTitle: 'Détails du produit',
      productCategoryLabel: 'Catégorie : ',
      productReferenceLabel: 'Référence : ',
      deliveryReturnsTitle: 'Livraison et retours',
      deliveryReturnsBody:
        'Les modalités de livraison et de retour dépendent de la structure. Contactez-la pour toute question.',
      viewOtherProducts: 'Voir les autres produits',
      productCharacteristicsHeading: 'Caractéristiques',
      productDescriptionHeading: 'Description',
    },
    reviews: {
      sectionTitle: 'Avis clients',
      loading: 'Chargement des avis…',
      noReviewsYet: 'Pas encore d’avis. Soyez le premier !',
      reviewCount: 'avis',
      yourReview: 'Votre avis',
      commentLabel: 'Commentaire (optionnel)',
      commentPlaceholder: 'Partagez votre expérience avec ce produit…',
      publish: 'Publier mon avis',
      sending: 'Envoi…',
      pickStars: 'Choisissez une note entre 1 et 5 étoiles.',
      loginToReview: 'Connectez-vous avec un compte client pour laisser un avis.',
      submitError: 'Impossible d’enregistrer l’avis.',
      recommendedBadge: 'Recommandé',
      ratingShort: 'note',
      sidebarReviews: 'Avis',
      dashboardTitle: 'Avis sur vos produits',
      delete: 'Supprimer',
      deleteConfirm: 'Supprimer cet avis ?',
      colProduct: 'Produit',
      colClient: 'Client',
      colNote: 'Note',
      colComment: 'Commentaire',
      colDate: 'Date',
      noReviewsDashboard: 'Aucun avis pour cette entreprise.',
    },
    chat: {
      fabAria: 'Ouvrir la messagerie',
      inboxTitle: 'Messages',
      threadTitle: 'Discussion',
      placeholder: 'Écrivez votre message…',
      send: 'Envoyer',
      photo: 'Photo',
      catalog: 'Catalogue',
      call: 'Appeler la structure',
      platformLineLabel: 'Ligne Rapido',
      platformDirectCallLabel: 'Appel téléphone',
      platformDirectCallButton: 'Appeler',
      platformDirectCallHint: 'Ouvre l’application Téléphone sur votre appareil.',
      platformCallStart: 'Appeler via Rapido',
      platformCallRinging: 'Sonnerie côté structure…',
      platformCallCancel: 'Annuler',
      platformCallHangup: 'Raccrocher',
      platformCallAcceptedHint: 'Connexion établie — poursuivez par message ou voix (audio navigateur à brancher).',
      incomingCallTitle: 'Appel Rapido entrant',
      incomingCallBody: 'Un client vous appelle depuis la messagerie.',
      incomingCallAccept: 'Décrocher',
      incomingCallReject: 'Refuser',
      attachProduct: 'Produit',
      report: 'Signaler',
      reportClient: 'Signaler le client',
      reportRestaurant: 'Signaler la structure',
      reason: 'Motif',
      submit: 'Envoyer',
      dashboardTitle: 'Messages clients',
      moderationTitle: 'Messagerie (toutes structures)',
      open: 'Ouvrir',
      noConversations: 'Aucune conversation',
      banned: 'Suspendu',
      ban: 'Suspendre',
      unban: 'Réactiver',
      shopChat: 'Chat',
      loading: 'Chargement…',
      backToList: 'Retour à la liste des messages',
      threadSubtitle: 'Messagerie avec la structure',
      catalogEmpty: 'Aucun produit listé pour l’instant.',
      errorThread: 'Impossible de charger cette conversation.',
      retry: 'Réessayer',
      emptyThread: 'Écrivez un message pour démarrer la discussion.',
      inboxSubtitle: 'Vos échanges avec les structures.',
      inboxEmptyHint: 'Ouvrez une fiche structure ou un produit pour contacter un vendeur.',
      noPreview: 'Aucun aperçu',
      inboxSearchPlaceholder: 'Rechercher une conversation…',
      inboxSearchNoMatch: 'Aucun résultat.',
      urgentAlertTitle: 'Alerte — demande client prioritaire',
      urgentAlertBody: 'Un client vient de formuler une demande via l’assistant. Consultez la conversation.',
      urgentAck: 'J’ai pris en charge',
    },
    supportWidget: {
      assistantLabel: 'Assistant Rapido',
      close: 'Fermer',
      greetingHi: 'Bonjour',
      howHelp: 'Comment pouvons-nous vous aider ?',
      statusOk: 'Statut : tous les services sont opérationnels',
      statusUpdated: 'Mis à jour',
      searchHelp: 'Rechercher une aide',
      shortcutWriteStructure: 'Écrire à une structure',
      shortcutWriteRapido: 'Contacter le service Rapido Flash',
      shortcutOrders: 'Suivre mes commandes',
      shortcutHelp: 'Centre d’aide',
      askQuestion: 'Poser une question',
      navHome: 'Accueil',
      navMessages: 'Messages',
      navHelp: 'Aide',
      navTasks: 'Tâches',
      tasksHint: 'Retrouvez vos commandes et livraisons.',
      openOrders: 'Ouvrir mes commandes',
      helpIntro: 'Astuces',
      helpBody:
        'Utilisez les raccourcis ci-dessus pour joindre une boutique ou l’équipe Rapido. L’assistant vous accueille dans chaque discussion et transmet votre demande aux bonnes personnes.',
      structuresTitle: 'Choisir une structure',
      back: 'Retour',
      platformLoading: 'Chargement du service Rapido…',
      platformUnavailable: 'Service Rapido indisponible pour le moment.',
      fabOpen: 'Ouvrir le centre d’aide',
      fabClose: 'Réduire',
    },
    install: {
      installTitle: 'Installation',
      alreadyInstalledTitle: 'Application déjà installée',
      alreadyInstalledBody:
        'L’application est déjà installée sur cet appareil. Vous pouvez la lancer depuis votre écran d’accueil (mobile) ou vos applications (desktop).',
      alreadyInstalledShort: "L'application est déjà installée !",
      promptUnavailableBody:
        "L'installation n'est pas encore disponible sur cet appareil pour le moment.\n\nLe bouton Download reste le moyen principal : réessayez dans quelques secondes après avoir continué la navigation sur Rapido.",
      soonAvailableBody:
        "L'installation sera bientôt disponible. Réessayez via le bouton Download dans quelques instants.",
      downloadTitle: "Télécharger l'application Rapido",
      soonTitle: 'Installation bientôt disponible',
      checkingTitle: 'Vérification en cours...',
      downloadCta: "Télécharger l’app",
      downloadNav: 'Télécharger',
      installingTitle: 'Installation en cours...',
      installingBody: "Veuillez patienter pendant l'installation de l'application",
      successTitle: 'Installation réussie !',
      successBody: "L'application Rapido a été installée avec succès.",
      successRedirect: "Ouverture de l'application...",
      iosModalTitle: 'Installer Rapido',
      iosModalDescIOS: "Ajoutez Rapido à votre écran d'accueil pour une expérience optimale",
      iosModalDescDesktop: "Ajoutez Rapido à votre Dock (macOS) ou installez l'application",
      iosStep1: 'Appuyez sur le bouton Partager (icône en bas de Safari)',
      iosStep1Hint: "(en bas de l'écran dans Safari)",
      iosStep2: 'Sélectionnez « Sur l’écran d’accueil »',
      iosStep2Hint: '(dans le menu de partage)',
      iosStep3: 'Appuyez sur "Ajouter"',
      iosStep3Hint: '(en haut à droite)',
      desktopStep1: "Dans la barre d'adresse, cliquez sur l'icône Partager",
      desktopStep1Hint: '(ou utilisez le menu Fichier → Partager)',
      desktopStep2: 'Sélectionnez « Ajouter à l’écran d’accueil »',
      desktopStep2Hint: '(ou "Add to Dock" sur macOS)',
      desktopStep3: 'Cliquez sur "Ajouter" pour confirmer',
      desktopStep3Hint: "(l'application apparaîtra dans votre Dock)",
      desktopTipTitle: 'Astuce : utilisez Chrome ou Edge pour une installation automatique',
      desktopTipBody: "Ces navigateurs proposent un bouton d'installation dans la barre d'adresse",
      understood: "J'ai compris",
      calloutEyebrow: 'Version application',
      calloutTitle: 'Installe Rapido sur mobile ou desktop',
      calloutDesc: 'Pour une expérience plus rapide et fluide, télécharge l’application quand tu veux.',
    },
  },
  en: {
      nav: {
      home: 'Home',
      cart: 'Cart',
      orders: 'Orders',
      invoices: 'Invoices',
      settings: 'Settings',
      logout: 'Log out',
    },
    navbar: {
      chooseAddress: 'Choose an address',
      modify: 'Modify',
      searchPlaceholder: 'Search for a product or shop...',
      userMenu: 'User menu',
      sectionCategories: 'Categories',
      sectionStructures: 'Structures',
      sectionProducts: 'Products',
      changeDeliveryAddress: 'Change delivery address',
      changeLanguage: 'Change language',
      language: 'Language',
    },
    home: {
      deliveryTo: 'Delivery to',
      selectAddress: 'Select an address',
      searchPlaceholder: 'Search for a product or shop...',
      productSearchTitle: 'Matching products',
      productSearchLoading: 'Searching…',
      productSearchEmpty: 'No products match. Here are some places to explore.',
      openShop: 'Open shop',
      addToCartShort: 'Cart',
      distanceKm: 'km',
      categories: 'Categories',
      all: 'All',
      noStructuresFound: 'No structures found',
      call: 'Call',
      whatsapp: 'WhatsApp',
      min: 'min',
      discoverStructures: 'Discover structures',
      previous: 'Previous',
      next: 'Next',
      freeDeliveryCotonou: 'Delivery is free in Cotonou. Enjoy ordering your favorite products!',
      gotIt: 'Got it',
      hideBannerToday: 'Hide for 24h',
      allProductsTitle: 'All products',
      allProductsEmpty: 'No products available for this category.',
      shopByCategory: 'Browse by category',
      railSwipeHint: 'Swipe to see more',
      productsListed: 'items',
      noProductsPreview: 'See the menu',
      promoOff: 'off',
      promoFreeDelivery: 'Free delivery',
      promoBadgesAria: 'Promotional offers on this product',
    },
    settings: {
      title: 'Settings',
      profilePhoto: 'Profile photo',
      changePhoto: 'Change photo',
      uploading: 'Uploading...',
      personalInfo: 'Personal information',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      notSet: 'Not set',
      editInfo: 'Edit information',
      deliveryAddress: 'Delivery address',
      noAddressDefined: 'No delivery address set',
      modifyAddress: 'Modify address',
      setAddress: 'Set an address',
      security: 'Security',
      changePassword: 'Change password',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmPassword: 'Confirm password',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving...',
      logout: 'Log out',
      yourName: 'Your name',
      yourEmail: 'Your email',
      yourPhone: 'Your phone number',
      photoUpdated: 'Photo updated successfully!',
      infoUpdated: 'Information updated successfully!',
      comingSoon: 'Coming soon',
      info: 'Information',
      invalidFormat: 'Invalid format',
      selectImage: 'Please select an image file',
      fileTooBig: 'Image must not exceed 500 MB',
      uploadError: 'Error uploading photo',
      updateError: 'Error updating',
      error: 'Error',
    },
    invoices: {
      title: 'My invoices / receipts',
      subtitle: 'Online payment receipts (Kkiapay)',
      empty: 'No digital invoices yet.',
      viewReceipt: 'View receipt',
      downloadReceipt: 'Download PDF',
      expired: 'Expired',
    },
    maintenance: {
      title: "We'll be right back",
      subtitle: 'The site is under maintenance',
      defaultMessage:
        "We're improving Rapido Flash for a better experience. Thank you for your patience — see you soon!",
      staffLogin: 'Pro login (dashboard)',
      dashboardTitle: 'Site maintenance',
      dashboardHint:
        'When maintenance is on, clients see a waiting page. You still have access to the dashboard.',
      toggleLabel: 'Put the site in maintenance mode',
      messageLabel: 'Message shown to visitors',
      messagePlaceholder: 'E.g. back in a few hours…',
      save: 'Save',
      saved: 'Settings saved',
      loadError: 'Could not load settings',
    },
    receipt: {
      title: 'Payment receipt',
      expiredMessage: 'This receipt is no longer valid (30 days passed).',
      print: 'Print',
      download: 'Download PDF',
      pdfError: 'Could not generate the PDF. Try again or use Print.',
      orderRef: 'Order reference',
      date: 'Date',
      amount: 'Amount paid',
      client: 'Customer',
      structure: 'Business',
      paidOnline: 'Online payment confirmed',
    },
    cart: {
      title: 'Cart',
      emptyTitle: 'Your cart is empty',
      emptySubtitle: 'Add products to get started',
      discoverStructures: 'Discover structures',
      subTotal: 'Subtotal',
      deliveryFee: 'Delivery fee',
      total: 'Total',
      checkout: 'Checkout',
      freeDeliveryPromoNote: 'Free delivery (product promo)',
    },
    locationEditor: {
      title: 'Change delivery address',
      instructionLabel: 'Delivery notes (required)',
      instructionPlaceholder: 'E.g. gate code, floor, landmarks…',
      telephoneLabel: 'Phone to call for delivery (required)',
      telephonePlaceholder: 'E.g. +229 …',
      searchPlaceholder: 'Search for an address...',
      useMyLocation: 'Use my location',
      selectedAddress: 'Selected address:',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving...',
      geolocError: 'Unable to get your position',
      geolocErrorTitle: 'Geolocation error',
      saveError: 'Error saving',
      hideMap: 'Hide map',
    },
    orders: {
      title: 'Orders',
      pageTitle: 'My orders',
      loading: 'Loading your orders…',
      noOrders: 'No orders yet',
      noOrdersBody: 'You have not placed an order yet.',
      browseProducts: 'Browse shops',
      totalLabel: 'Total',
      viewReceipt: 'View receipt / invoice',
      followOrder: 'Track my order',
      followOrderAria: 'Track my order',
      statusPending: 'Pending',
      statusConfirmed: 'Confirmed',
      statusPreparing: 'Preparing',
      statusDelivery: 'Out for delivery',
      statusDelivered: 'Delivered',
      statusCancelled: 'Cancelled',
      paymentCash: 'Cash on delivery',
      paymentMomoBefore: 'Mobile Money before delivery',
      paymentMomoAfter: 'Mobile Money after delivery',
      whatsappPaidLine: 'OK - Online payment (MoMo): received',
      whatsappTemplate:
        'Hello Rapido Flash team\n\n' +
        'I would like to track my order placed on the app and know its status.\n\n' +
        '--------------------------------\n' +
        'ORDER SUMMARY\n' +
        '--------------------------------\n' +
        '- Short reference: {{ref}}\n' +
        '- Order ID: {{id}}\n' +
        '- Shop: {{shop}}\n' +
        '- Date: {{date}}\n' +
        '- Status in the app: {{status}}\n' +
        '- Items subtotal: {{subtotal}} FCFA\n' +
        '- Delivery fee: {{shipping}} FCFA\n' +
        '- Total: {{total}} FCFA\n' +
        '- Payment method: {{payment}}\n' +
        '{{paidExtra}}\n\n' +
        '--------------------------------\n' +
        'DELIVERY\n' +
        '--------------------------------\n' +
        '- Address: {{address}}\n' +
        '- Delivery phone: {{deliveryPhone}}\n' +
        '- Instructions: {{instruction}}\n\n' +
        '--------------------------------\n' +
        'LINE ITEMS\n' +
        '--------------------------------\n' +
        '{{items}}\n\n' +
        '--------------------------------\n' +
        'CUSTOMER\n' +
        '--------------------------------\n' +
        '- Name: {{clientName}}\n' +
        '- Email: {{clientEmail}}\n' +
        '- Account phone: {{accountPhone}}\n\n' +
        'Please keep me updated on my order.\n\n' +
        'Kind regards,\n' +
        '{{clientName}}',
    },
    checkout: {
      title: 'Payment',
      pay: 'Pay',
      processing: 'Processing...',
      selectAddress: 'Please select a delivery address',
      addressRequired: 'Address required',
      paymentSuccess: 'Payment successful!',
      paymentSuccessTitle: 'Payment successful',
      paymentCancelled: 'Payment cancelled or failed',
      paymentError: 'Payment error. Please try again.',
      serviceError: 'Payment service unavailable. Please refresh and try again.',
      orderError: 'Order error. Please try again.',
      paymentMethod: 'Payment method',
      cashOnDelivery: 'Cash on delivery',
      cashOnDeliveryHint: 'You pay cash to the courier.',
      momoBefore: 'Mobile Money before delivery',
      momoBeforeHint: 'Pay online (MoMo) now, then delivery.',
      momoAfter: 'Mobile Money after delivery',
      momoAfterHint: 'Order placed; you will pay by MoMo on receipt.',
      confirmOrder: 'Confirm order',
      orderCreated: 'Order placed!',
      telephoneRequired: 'Delivery phone number is required (at least 8 digits).',
      instructionRequired: 'Delivery instructions are required (gate code, floor, landmarks, etc.).',
      openMapToChoose: 'Show map to pick the exact spot',
      deliveryAddressTitle: 'Delivery address',
      backToCart: 'Back',
      finalizeTitle: 'Complete your order',
      recapTitle: 'Order summary',
      selectedAddressLabel: 'Address',
      useCurrentLocation: 'Use my current location',
      chooseOnMap: 'Choose on the map',
      paymentStepTitle: 'Payment method',
      paymentStepSubtitle: 'Choose how you want to pay',
      continueToDelivery: 'Continue to delivery',
      addressModalTitle: 'Delivery address',
      addressModalSubtitle: 'Search for an address or use your location.',
      confirmAndOrder: 'Confirm and place order',
      successTitle: 'Thank you! Your order is placed',
      successSubtitle: 'Summary below. Track your order on WhatsApp or open your orders list.',
      viewOrders: 'View my orders',
      backHome: 'Back to home',
    },
    common: {
      cancel: 'Cancel',
      save: 'Save',
      modify: 'Modify',
      user: 'User',
      profile: 'Profile',
      french: 'Français',
      english: 'English',
      error: 'Error',
    },
    i18n: {
      nameEn: 'Name (English)',
      nameEnHint: 'Optional. Shown when the site language is English.',
      descEn: 'Description (English)',
      productNameEn: 'Product name (English)',
      productDescEn: 'Description (English)',
      homeCardNameEn: 'Home card name (English)',
      structureNameEn: 'Business name (English)',
      structureDescEn: 'Description (English)',
      productCharacteristics: 'Characteristics',
      productCharacteristicsHint: 'One line = one bullet. Shown under “Product details” on the shop product page.',
      productCharacteristicsEn: 'Characteristics (English)',
      productPromoSection: 'Promotions (cards & checkout)',
      promoFreeShippingLabel: 'Highlight free delivery: if the order includes this product, delivery fees are waived.',
      promoPercentLabel: 'Price discount (%)',
      promoPercentHint: 'Between 1 and 90, or leave empty to disable. The paid price is calculated automatically.',
      productDescriptionFormatHint:
        'Line breaks: press Enter. A blank line starts a new paragraph. Bold: **text** or __text__. Link: [label](https://…) — only http or https URLs.',
      productDescriptionPreview: 'Preview (as on the product page)',
      productRecommended: 'Featured product',
      productRecommendedHint: 'Shows a “Recommended” badge on the product page and home cards (alongside reviews).',
    },
    store: {
      loading: 'Loading shop...',
      notFound: 'Shop not found',
      notFoundDesc: 'This shop does not exist or was removed.',
      backHome: 'Back to home',
      back: 'Back',
      productSearchPlaceholder: 'Search products',
      productSearchAria: 'Search products in this shop',
      orderDaysLabel: 'Order / sales days:',
      orderDayBefore: 'Consider ordering the day before to be delivered on the planned day.',
      filterAll: 'All',
      filterAllProducts: 'All products',
      menu: 'Menu',
      cartTitle: 'Cart',
      contact: 'Contact',
      callTitle: 'Call',
      whatsappTitle: 'Contact on WhatsApp',
      noProducts: 'No products available',
      noProductsStructure: 'No products for this shop.',
      noProductsCategory: 'No products in this category.',
      noProductsCategoryDesktop: 'No products in this category.',
      cartEmpty: 'Add an item to get started',
      total: 'Total',
      viewCart: 'View cart',
      articles: 'item(s)',
      addToCart: 'Add to cart',
      buy: 'Buy',
      share: 'Share',
      zoomAlt: 'Enlarged view',
      close: 'Close',
      productPageAria: 'Product page',
      productDefaultEyebrow: 'Product',
      productGalleryThumbsAria: 'More product views',
      zoomHint: 'Click the photo to zoom.',
      productDetailsTitle: 'Product details',
      productCategoryLabel: 'Category: ',
      productReferenceLabel: 'Reference: ',
      deliveryReturnsTitle: 'Shipping & returns',
      deliveryReturnsBody:
        'Delivery and return policies depend on the shop. Contact them for details.',
      viewOtherProducts: 'See more products',
      productCharacteristicsHeading: 'Features',
      productDescriptionHeading: 'Description',
    },
    reviews: {
      sectionTitle: 'Customer reviews',
      loading: 'Loading reviews…',
      noReviewsYet: 'No reviews yet. Be the first!',
      reviewCount: 'reviews',
      yourReview: 'Your review',
      commentLabel: 'Comment (optional)',
      commentPlaceholder: 'Share your experience with this product…',
      publish: 'Post review',
      sending: 'Sending…',
      pickStars: 'Please choose a rating from 1 to 5 stars.',
      loginToReview: 'Sign in with a customer account to leave a review.',
      submitError: 'Could not save your review.',
      recommendedBadge: 'Recommended',
      ratingShort: 'rating',
      sidebarReviews: 'Reviews',
      dashboardTitle: 'Product reviews',
      delete: 'Delete',
      deleteConfirm: 'Delete this review?',
      colProduct: 'Product',
      colClient: 'Customer',
      colNote: 'Rating',
      colComment: 'Comment',
      colDate: 'Date',
      noReviewsDashboard: 'No reviews for this business yet.',
    },
    chat: {
      fabAria: 'Open messaging',
      inboxTitle: 'Messages',
      threadTitle: 'Chat',
      placeholder: 'Type a message…',
      send: 'Send',
      photo: 'Photo',
      catalog: 'Catalog',
      call: 'Call the shop',
      platformLineLabel: 'Rapido line',
      platformDirectCallLabel: 'Phone call',
      platformDirectCallButton: 'Call',
      platformDirectCallHint: 'Opens the Phone app on your device.',
      platformCallStart: 'Call via Rapido',
      platformCallRinging: 'Ringing the business…',
      platformCallCancel: 'Cancel',
      platformCallHangup: 'Hang up',
      platformCallAcceptedHint: 'Connected — continue in chat or voice (in-browser audio coming soon).',
      incomingCallTitle: 'Incoming Rapido call',
      incomingCallBody: 'A customer is calling from messaging.',
      incomingCallAccept: 'Answer',
      incomingCallReject: 'Decline',
      attachProduct: 'Product',
      report: 'Report',
      reportClient: 'Report customer',
      reportRestaurant: 'Report business',
      reason: 'Reason',
      submit: 'Submit',
      dashboardTitle: 'Customer messages',
      moderationTitle: 'Messaging (all businesses)',
      open: 'Open',
      noConversations: 'No conversations yet',
      banned: 'Suspended',
      ban: 'Suspend',
      unban: 'Reinstate',
      shopChat: 'Chat',
      loading: 'Loading…',
      backToList: 'Back to messages',
      threadSubtitle: 'Messaging with this business',
      catalogEmpty: 'No products listed yet.',
      errorThread: 'Could not load this conversation.',
      retry: 'Try again',
      emptyThread: 'Send a message to start the conversation.',
      inboxSubtitle: 'Your conversations with businesses.',
      inboxEmptyHint: 'Open a shop or product page to message a seller.',
      noPreview: 'No preview',
      inboxSearchPlaceholder: 'Search conversations…',
      inboxSearchNoMatch: 'No match.',
      urgentAlertTitle: 'Alert — priority customer request',
      urgentAlertBody: 'A customer just sent a request through the assistant. Open the conversation.',
      urgentAck: 'Acknowledge',
    },
    supportWidget: {
      assistantLabel: 'Rapido assistant',
      close: 'Close',
      greetingHi: 'Hello',
      howHelp: 'How can we help?',
      statusOk: 'Status: all systems operational',
      statusUpdated: 'Updated',
      searchHelp: 'Search for help',
      shortcutWriteStructure: 'Message a business',
      shortcutWriteRapido: 'Contact Rapido Flash support',
      shortcutOrders: 'Track my orders',
      shortcutHelp: 'Help center',
      askQuestion: 'Ask a question',
      navHome: 'Home',
      navMessages: 'Messages',
      navHelp: 'Help',
      navTasks: 'Tasks',
      tasksHint: 'View your orders and deliveries.',
      openOrders: 'Open my orders',
      helpIntro: 'Tips',
      helpBody:
        'Use the shortcuts above to reach a shop or the Rapido team. The assistant greets you in every thread and forwards your request to the right people.',
      structuresTitle: 'Choose a business',
      back: 'Back',
      platformLoading: 'Loading Rapido support…',
      platformUnavailable: 'Rapido support is not available right now.',
      fabOpen: 'Open help center',
      fabClose: 'Minimize',
    },
    install: {
      installTitle: 'Installation',
      alreadyInstalledTitle: 'App already installed',
      alreadyInstalledBody:
        'The app is already installed on this device. You can open it from your home screen (mobile) or applications (desktop).',
      alreadyInstalledShort: 'The app is already installed!',
      promptUnavailableBody:
        'Installation is not available on this device yet.\n\nThe Download button remains the primary way: try again in a few seconds while continuing to browse Rapido.',
      soonAvailableBody:
        'Installation will be available shortly. Please try again using the Download button.',
      downloadTitle: 'Download Rapido app',
      soonTitle: 'Installation coming soon',
      checkingTitle: 'Checking availability...',
      downloadCta: 'Download app',
      downloadNav: 'Download',
      installingTitle: 'Installing...',
      installingBody: 'Please wait while the app is being installed.',
      successTitle: 'Installation successful!',
      successBody: 'Rapido app has been installed successfully.',
      successRedirect: 'Opening the app...',
      iosModalTitle: 'Install Rapido',
      iosModalDescIOS: 'Add Rapido to your home screen for the best experience',
      iosModalDescDesktop: 'Add Rapido to your Dock (macOS) or install the app',
      iosStep1: 'Tap the Share button (bottom of Safari)',
      iosStep1Hint: '(at the bottom in Safari)',
      iosStep2: 'Select "Add to Home Screen"',
      iosStep2Hint: '(from the share menu)',
      iosStep3: 'Tap "Add"',
      iosStep3Hint: '(top-right corner)',
      desktopStep1: 'In the address bar, click the Share icon',
      desktopStep1Hint: '(or use File → Share)',
      desktopStep2: 'Select "Add to Home Screen"',
      desktopStep2Hint: '(or "Add to Dock" on macOS)',
      desktopStep3: 'Click "Add" to confirm',
      desktopStep3Hint: '(the app will appear in your Dock)',
      desktopTipTitle: 'Tip: use Chrome or Edge for automatic install',
      desktopTipBody: 'These browsers provide an install button in the address bar',
      understood: 'Got it',
      calloutEyebrow: 'App version',
      calloutTitle: 'Install Rapido on mobile or desktop',
      calloutDesc: 'For a faster and smoother experience, download the app whenever you want.',
    },
  },
};

const LanguageContext = createContext({
  language: 'fr',
  setLanguage: () => {},
  t: (key) => key,
  localized: () => '',
  productDisplayName: () => '',
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem(STORAGE_KEY) || 'fr';
    } catch {
      return 'fr';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch (e) {
      // ignore
    }
  }, [language]);

  const setLanguage = useCallback((lang) => {
    if (lang === 'fr' || lang === 'en') setLanguageState(lang);
  }, []);

  const t = useCallback((namespace, key) => {
    const ns = translations[language]?.[namespace];
    return (ns && ns[key]) || translations.fr[namespace]?.[key] || key;
  }, [language]);

  const contextValue = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      localized: (obj, field) => pickLocalized(language, obj, field),
      productDisplayName: (p) => pickProductDisplayName(language, p),
    }),
    [language, setLanguage, t]
  );

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
