import React, { createContext, useState, useEffect, useCallback, useMemo } from 'react';
import { pickLocalized, pickProductDisplayName } from '../utils/i18nContent';

const STORAGE_KEY = 'rapido_lang';

export const translations = {
  fr: {
      nav: {
      home: 'Accueil',
      cart: 'Panier',
      orders: 'Commandes',
      invoices: 'Factures',
      settings: 'Paramètres',
      logout: 'Déconnexion',
    },
    navbar: {
      chooseAddress: 'Choisir une adresse',
      modify: 'Modifier',
      searchPlaceholder: 'Rechercher un produit, une boutique...',
      userMenu: 'Menu utilisateur',
      sectionCategories: 'Catégories',
      sectionStructures: 'Structures',
      sectionProducts: 'Produits',
      changeDeliveryAddress: "Modifier l'adresse de livraison",
      changeLanguage: 'Changer la langue',
      language: 'Langue',
    },
    home: {
      deliveryTo: 'Livraison à',
      selectAddress: 'Sélectionner une adresse',
      searchPlaceholder: 'Rechercher un produit, une boutique...',
      productSearchTitle: 'Produits trouvés',
      productSearchLoading: 'Recherche en cours…',
      productSearchEmpty: 'Aucun produit ne correspond. Voici des structures à explorer.',
      openShop: 'Voir la boutique',
      addToCartShort: 'Panier',
      distanceKm: 'km',
      categories: 'Catégories',
      all: 'Tous',
      noStructuresFound: 'Aucune structure trouvée',
      call: 'Appeler',
      whatsapp: 'WhatsApp',
      min: 'min',
      discoverStructures: 'Découvrir les structures',
      previous: 'Précédent',
      next: 'Suivant',
      freeDeliveryCotonou: 'La livraison est gratuite à Cotonou. Profitez-en pour commander vos produits préférés !',
      gotIt: "J'ai compris",
      hideBannerToday: 'Masquer pour 24 h',
      allProductsTitle: 'Tous les produits',
      allProductsEmpty: 'Aucun produit disponible pour cette catégorie.',
      noProductsPreview: 'Découvrir la carte',
      promoOff: 'promo',
      promoFreeDelivery: 'Livraison gratuite',
      promoBadgesAria: 'Offres promotionnelles sur ce produit',
    },
    settings: {
      title: 'Paramètres',
      profilePhoto: 'Photo de profil',
      changePhoto: 'Changer la photo',
      uploading: 'Upload en cours...',
      personalInfo: 'Informations personnelles',
      name: 'Nom',
      email: 'Email',
      phone: 'Téléphone',
      notSet: 'Non défini',
      editInfo: 'Modifier les informations',
      deliveryAddress: 'Adresse de livraison',
      noAddressDefined: 'Aucune adresse de livraison définie',
      modifyAddress: "Modifier l'adresse",
      setAddress: 'Définir une adresse',
      security: 'Sécurité',
      changePassword: 'Changer le mot de passe',
      currentPassword: 'Mot de passe actuel',
      newPassword: 'Nouveau mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      cancel: 'Annuler',
      save: 'Enregistrer',
      saving: 'Enregistrement...',
      logout: 'Se déconnecter',
      yourName: 'Votre nom',
      yourEmail: 'Votre email',
      yourPhone: 'Votre numéro de téléphone',
      photoUpdated: 'Photo mise à jour avec succès !',
      infoUpdated: 'Informations mises à jour avec succès !',
      comingSoon: 'Fonctionnalité à venir',
      info: 'Information',
      invalidFormat: 'Format invalide',
      selectImage: 'Veuillez sélectionner un fichier image',
      fileTooBig: "L'image ne doit pas dépasser 500 Mo",
      uploadError: "Erreur lors de l'upload de la photo",
      updateError: 'Erreur lors de la mise à jour',
      error: 'Erreur',
    },
    invoices: {
      title: 'Mes factures / reçus',
      subtitle: 'Reçus de paiement en ligne (Kkiapay)',
      empty: 'Aucune facture numérique pour le moment.',
      viewReceipt: 'Voir le reçu',
      downloadReceipt: 'Télécharger',
      expired: 'Expiré',
    },
    maintenance: {
      title: 'On revient tout de suite',
      subtitle: 'Le site est en maintenance',
      defaultMessage:
        'Nous améliorons Rapido Flash pour vous offrir une meilleure expérience. Merci de votre patience — à très vite !',
      staffLogin: 'Connexion espace pro (tableau de bord)',
      dashboardTitle: 'Maintenance du site',
      dashboardHint:
        'Lorsque la maintenance est activée, les clients voient une page d’attente. Vous gardez l’accès au tableau de bord.',
      toggleLabel: 'Mettre le site en maintenance',
      messageLabel: 'Message affiché aux visiteurs',
      messagePlaceholder: 'Ex. : retour prévu dans quelques heures…',
      save: 'Enregistrer',
      saved: 'Paramètres enregistrés',
      loadError: 'Impossible de charger les paramètres',
    },
    receipt: {
      title: 'Reçu de paiement',
      expiredMessage: 'Ce reçu n’est plus valide (30 jours dépassés).',
      print: 'Imprimer / PDF',
      download: 'Télécharger (HTML)',
      orderRef: 'Référence commande',
      date: 'Date',
      amount: 'Montant payé',
      client: 'Client',
      structure: 'Structure',
      paidOnline: 'Paiement en ligne confirmé',
    },
    cart: {
      title: 'Panier',
      emptyTitle: 'Votre panier est vide',
      emptySubtitle: 'Ajoutez des produits pour commencer',
      discoverStructures: 'Découvrir les structures',
      subTotal: 'Sous-total',
      deliveryFee: 'Frais de livraison',
      total: 'Total',
      checkout: 'Passer la commande',
      freeDeliveryPromoNote: 'Livraison offerte (promo produit)',
    },
    locationEditor: {
      title: "Modifier l'adresse de livraison",
      instructionLabel: 'Indications pour le livreur (optionnel)',
      instructionPlaceholder: 'Ex. : code portail, étage, repères…',
      telephoneLabel: 'Numéro à appeler pour la livraison (optionnel)',
      telephonePlaceholder: 'Ex. : +229 …',
      searchPlaceholder: 'Rechercher une adresse...',
      useMyLocation: 'Utiliser ma position',
      selectedAddress: 'Adresse sélectionnée :',
      cancel: 'Annuler',
      save: 'Enregistrer',
      saving: 'Enregistrement...',
      geolocError: 'Impossible de récupérer votre position',
      geolocErrorTitle: 'Erreur de géolocalisation',
      saveError: 'Erreur lors de la sauvegarde',
    },
    orders: {
      title: 'Commandes',
      noOrders: 'Aucune commande',
      statusPending: 'En attente',
      statusConfirmed: 'Confirmée',
      statusPreparing: 'En préparation',
      statusDelivery: 'En livraison',
      statusDelivered: 'Livrée',
      statusCancelled: 'Annulée',
    },
    checkout: {
      title: 'Paiement',
      pay: 'Payer',
      processing: 'Traitement...',
      selectAddress: 'Veuillez sélectionner une adresse de livraison',
      addressRequired: 'Adresse requise',
      paymentSuccess: 'Paiement effectué avec succès !',
      paymentSuccessTitle: 'Paiement réussi',
      paymentCancelled: 'Paiement annulé ou échoué',
      paymentError: 'Erreur lors du paiement. Veuillez réessayer.',
      serviceError: 'Service de paiement non disponible. Veuillez rafraîchir la page et réessayer.',
      orderError: 'Erreur lors de la commande. Veuillez réessayer.',
      paymentMethod: 'Mode de paiement',
      cashOnDelivery: 'Espèces à la livraison',
      cashOnDeliveryHint: 'Vous payez en liquide au livreur.',
      momoBefore: 'Mobile Money avant la livraison',
      momoBeforeHint: 'Paiement en ligne (MoMo) maintenant, puis livraison.',
      momoAfter: 'Mobile Money après la livraison',
      momoAfterHint: 'Commande enregistrée ; vous paierez en MoMo à réception.',
      confirmOrder: 'Confirmer la commande',
      orderCreated: 'Commande enregistrée !',
    },
    common: {
      cancel: 'Annuler',
      save: 'Enregistrer',
      modify: 'Modifier',
      user: 'Utilisateur',
      profile: 'Profil',
      french: 'Français',
      english: 'English',
      error: 'Erreur',
    },
    i18n: {
      nameEn: 'Nom (anglais)',
      nameEnHint: 'Optionnel. Affiché quand la langue du site est « English ».',
      descEn: 'Description (anglais)',
      productNameEn: 'Nom produit (anglais)',
      productDescEn: 'Description (anglais)',
      homeCardNameEn: 'Nom carte d’accueil (anglais)',
      structureNameEn: 'Nom de la structure (anglais)',
      structureDescEn: 'Description (anglais)',
      productCharacteristics: 'Caractéristiques',
      productCharacteristicsHint: 'Une ligne = un point. Affiché dans « Détails du produit » sur la page boutique (fiche produit).',
      productCharacteristicsEn: 'Caractéristiques (anglais)',
      productPromoSection: 'Promotions (cartes & commande)',
      promoFreeShippingLabel: 'Mettre en avant la livraison gratuite : si la commande contient ce produit, les frais de livraison sont offerts.',
      promoPercentLabel: 'Réduction de prix (%)',
      promoPercentHint: 'Entre 1 et 90, ou vide pour désactiver. Le prix payé est calculé automatiquement.',
      productDescriptionFormatHint:
        'Retours à la ligne : utilisez Entrée. Une ligne vide sépare deux paragraphes. Gras : **texte** ou __texte__. Lien : [libellé](https://…) — uniquement des adresses en http ou https.',
      productDescriptionPreview: 'Aperçu (comme sur la fiche produit)',
    },
    store: {
      loading: 'Chargement de la structure...',
      notFound: 'Structure non trouvée',
      notFoundDesc: "La structure demandée n'existe pas ou a été supprimée.",
      backHome: "Retour à l'accueil",
      back: 'Retour',
      productSearchPlaceholder: 'Recherche de produits',
      productSearchAria: 'Recherche de produits dans cette boutique',
      orderDaysLabel: 'Jours de commande / vente :',
      orderDayBefore: 'Pensez à commander la veille pour être livré le jour prévu.',
      filterAll: 'Tous',
      filterAllProducts: 'Tous les produits',
      menu: 'Menu',
      cartTitle: 'Chariot',
      contact: 'Contact',
      callTitle: 'Appeler',
      whatsappTitle: 'Contacter par WhatsApp',
      noProducts: 'Aucun produit disponible',
      noProductsStructure: 'Aucun produit pour cette structure.',
      noProductsCategory: 'Aucun produit dans cette catégorie.',
      noProductsCategoryDesktop: 'Aucun produit dans cette catégorie.',
      cartEmpty: 'Ajouter un élément pour commencer',
      total: 'Total',
      viewCart: 'Voir le panier',
      articles: 'article(s)',
      addToCart: 'Ajouter au panier',
      share: 'Partager',
      zoomAlt: 'Vue agrandie',
      close: 'Fermer',
      productPageAria: 'Fiche produit',
      productDefaultEyebrow: 'Produit',
      productGalleryThumbsAria: 'Autres vues du produit',
      zoomHint: 'Cliquez sur la photo pour agrandir.',
      productDetailsTitle: 'Détails du produit',
      productCategoryLabel: 'Catégorie : ',
      productReferenceLabel: 'Référence : ',
      deliveryReturnsTitle: 'Livraison et retours',
      deliveryReturnsBody:
        'Les modalités de livraison et de retour dépendent de la structure. Contactez-la pour toute question.',
      viewOtherProducts: 'Voir les autres produits',
      productCharacteristicsHeading: 'Caractéristiques',
      productDescriptionHeading: 'Description',
    },
  },
  en: {
      nav: {
      home: 'Home',
      cart: 'Cart',
      orders: 'Orders',
      invoices: 'Invoices',
      settings: 'Settings',
      logout: 'Log out',
    },
    navbar: {
      chooseAddress: 'Choose an address',
      modify: 'Modify',
      searchPlaceholder: 'Search for a product or shop...',
      userMenu: 'User menu',
      sectionCategories: 'Categories',
      sectionStructures: 'Structures',
      sectionProducts: 'Products',
      changeDeliveryAddress: 'Change delivery address',
      changeLanguage: 'Change language',
      language: 'Language',
    },
    home: {
      deliveryTo: 'Delivery to',
      selectAddress: 'Select an address',
      searchPlaceholder: 'Search for a product or shop...',
      productSearchTitle: 'Matching products',
      productSearchLoading: 'Searching…',
      productSearchEmpty: 'No products match. Here are some places to explore.',
      openShop: 'Open shop',
      addToCartShort: 'Cart',
      distanceKm: 'km',
      categories: 'Categories',
      all: 'All',
      noStructuresFound: 'No structures found',
      call: 'Call',
      whatsapp: 'WhatsApp',
      min: 'min',
      discoverStructures: 'Discover structures',
      previous: 'Previous',
      next: 'Next',
      freeDeliveryCotonou: 'Delivery is free in Cotonou. Enjoy ordering your favorite products!',
      gotIt: 'Got it',
      hideBannerToday: 'Hide for 24h',
      allProductsTitle: 'All products',
      allProductsEmpty: 'No products available for this category.',
      noProductsPreview: 'See the menu',
      promoOff: 'off',
      promoFreeDelivery: 'Free delivery',
      promoBadgesAria: 'Promotional offers on this product',
    },
    settings: {
      title: 'Settings',
      profilePhoto: 'Profile photo',
      changePhoto: 'Change photo',
      uploading: 'Uploading...',
      personalInfo: 'Personal information',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      notSet: 'Not set',
      editInfo: 'Edit information',
      deliveryAddress: 'Delivery address',
      noAddressDefined: 'No delivery address set',
      modifyAddress: 'Modify address',
      setAddress: 'Set an address',
      security: 'Security',
      changePassword: 'Change password',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmPassword: 'Confirm password',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving...',
      logout: 'Log out',
      yourName: 'Your name',
      yourEmail: 'Your email',
      yourPhone: 'Your phone number',
      photoUpdated: 'Photo updated successfully!',
      infoUpdated: 'Information updated successfully!',
      comingSoon: 'Coming soon',
      info: 'Information',
      invalidFormat: 'Invalid format',
      selectImage: 'Please select an image file',
      fileTooBig: 'Image must not exceed 500 MB',
      uploadError: 'Error uploading photo',
      updateError: 'Error updating',
      error: 'Error',
    },
    invoices: {
      title: 'My invoices / receipts',
      subtitle: 'Online payment receipts (Kkiapay)',
      empty: 'No digital invoices yet.',
      viewReceipt: 'View receipt',
      downloadReceipt: 'Download',
      expired: 'Expired',
    },
    maintenance: {
      title: "We'll be right back",
      subtitle: 'The site is under maintenance',
      defaultMessage:
        "We're improving Rapido Flash for a better experience. Thank you for your patience — see you soon!",
      staffLogin: 'Pro login (dashboard)',
      dashboardTitle: 'Site maintenance',
      dashboardHint:
        'When maintenance is on, clients see a waiting page. You still have access to the dashboard.',
      toggleLabel: 'Put the site in maintenance mode',
      messageLabel: 'Message shown to visitors',
      messagePlaceholder: 'E.g. back in a few hours…',
      save: 'Save',
      saved: 'Settings saved',
      loadError: 'Could not load settings',
    },
    receipt: {
      title: 'Payment receipt',
      expiredMessage: 'This receipt is no longer valid (30 days passed).',
      print: 'Print / PDF',
      download: 'Download (HTML)',
      orderRef: 'Order reference',
      date: 'Date',
      amount: 'Amount paid',
      client: 'Customer',
      structure: 'Business',
      paidOnline: 'Online payment confirmed',
    },
    cart: {
      title: 'Cart',
      emptyTitle: 'Your cart is empty',
      emptySubtitle: 'Add products to get started',
      discoverStructures: 'Discover structures',
      subTotal: 'Subtotal',
      deliveryFee: 'Delivery fee',
      total: 'Total',
      checkout: 'Checkout',
      freeDeliveryPromoNote: 'Free delivery (product promo)',
    },
    locationEditor: {
      title: 'Change delivery address',
      instructionLabel: 'Delivery notes (optional)',
      instructionPlaceholder: 'E.g. gate code, floor, landmarks…',
      telephoneLabel: 'Phone to call for delivery (optional)',
      telephonePlaceholder: 'E.g. +229 …',
      searchPlaceholder: 'Search for an address...',
      useMyLocation: 'Use my location',
      selectedAddress: 'Selected address:',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving...',
      geolocError: 'Unable to get your position',
      geolocErrorTitle: 'Geolocation error',
      saveError: 'Error saving',
    },
    orders: {
      title: 'Orders',
      noOrders: 'No orders',
      statusPending: 'Pending',
      statusConfirmed: 'Confirmed',
      statusPreparing: 'Preparing',
      statusDelivery: 'Out for delivery',
      statusDelivered: 'Delivered',
      statusCancelled: 'Cancelled',
    },
    checkout: {
      title: 'Payment',
      pay: 'Pay',
      processing: 'Processing...',
      selectAddress: 'Please select a delivery address',
      addressRequired: 'Address required',
      paymentSuccess: 'Payment successful!',
      paymentSuccessTitle: 'Payment successful',
      paymentCancelled: 'Payment cancelled or failed',
      paymentError: 'Payment error. Please try again.',
      serviceError: 'Payment service unavailable. Please refresh and try again.',
      orderError: 'Order error. Please try again.',
      paymentMethod: 'Payment method',
      cashOnDelivery: 'Cash on delivery',
      cashOnDeliveryHint: 'You pay cash to the courier.',
      momoBefore: 'Mobile Money before delivery',
      momoBeforeHint: 'Pay online (MoMo) now, then delivery.',
      momoAfter: 'Mobile Money after delivery',
      momoAfterHint: 'Order placed; you will pay by MoMo on receipt.',
      confirmOrder: 'Confirm order',
      orderCreated: 'Order placed!',
    },
    common: {
      cancel: 'Cancel',
      save: 'Save',
      modify: 'Modify',
      user: 'User',
      profile: 'Profile',
      french: 'Français',
      english: 'English',
      error: 'Error',
    },
    i18n: {
      nameEn: 'Name (English)',
      nameEnHint: 'Optional. Shown when the site language is English.',
      descEn: 'Description (English)',
      productNameEn: 'Product name (English)',
      productDescEn: 'Description (English)',
      homeCardNameEn: 'Home card name (English)',
      structureNameEn: 'Business name (English)',
      structureDescEn: 'Description (English)',
      productCharacteristics: 'Characteristics',
      productCharacteristicsHint: 'One line = one bullet. Shown under “Product details” on the shop product page.',
      productCharacteristicsEn: 'Characteristics (English)',
      productPromoSection: 'Promotions (cards & checkout)',
      promoFreeShippingLabel: 'Highlight free delivery: if the order includes this product, delivery fees are waived.',
      promoPercentLabel: 'Price discount (%)',
      promoPercentHint: 'Between 1 and 90, or leave empty to disable. The paid price is calculated automatically.',
      productDescriptionFormatHint:
        'Line breaks: press Enter. A blank line starts a new paragraph. Bold: **text** or __text__. Link: [label](https://…) — only http or https URLs.',
      productDescriptionPreview: 'Preview (as on the product page)',
    },
    store: {
      loading: 'Loading shop...',
      notFound: 'Shop not found',
      notFoundDesc: 'This shop does not exist or was removed.',
      backHome: 'Back to home',
      back: 'Back',
      productSearchPlaceholder: 'Search products',
      productSearchAria: 'Search products in this shop',
      orderDaysLabel: 'Order / sales days:',
      orderDayBefore: 'Consider ordering the day before to be delivered on the planned day.',
      filterAll: 'All',
      filterAllProducts: 'All products',
      menu: 'Menu',
      cartTitle: 'Cart',
      contact: 'Contact',
      callTitle: 'Call',
      whatsappTitle: 'Contact on WhatsApp',
      noProducts: 'No products available',
      noProductsStructure: 'No products for this shop.',
      noProductsCategory: 'No products in this category.',
      noProductsCategoryDesktop: 'No products in this category.',
      cartEmpty: 'Add an item to get started',
      total: 'Total',
      viewCart: 'View cart',
      articles: 'item(s)',
      addToCart: 'Add to cart',
      share: 'Share',
      zoomAlt: 'Enlarged view',
      close: 'Close',
      productPageAria: 'Product page',
      productDefaultEyebrow: 'Product',
      productGalleryThumbsAria: 'More product views',
      zoomHint: 'Click the photo to zoom.',
      productDetailsTitle: 'Product details',
      productCategoryLabel: 'Category: ',
      productReferenceLabel: 'Reference: ',
      deliveryReturnsTitle: 'Shipping & returns',
      deliveryReturnsBody:
        'Delivery and return policies depend on the shop. Contact them for details.',
      viewOtherProducts: 'See more products',
      productCharacteristicsHeading: 'Features',
      productDescriptionHeading: 'Description',
    },
  },
};

const LanguageContext = createContext({
  language: 'fr',
  setLanguage: () => {},
  t: (key) => key,
  localized: () => '',
  productDisplayName: () => '',
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem(STORAGE_KEY) || 'fr';
    } catch {
      return 'fr';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch (e) {
      // ignore
    }
  }, [language]);

  const setLanguage = useCallback((lang) => {
    if (lang === 'fr' || lang === 'en') setLanguageState(lang);
  }, []);

  const t = useCallback((namespace, key) => {
    const ns = translations[language]?.[namespace];
    return (ns && ns[key]) || translations.fr[namespace]?.[key] || key;
  }, [language]);

  const contextValue = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      localized: (obj, field) => pickLocalized(language, obj, field),
      productDisplayName: (p) => pickProductDisplayName(language, p),
    }),
    [language, setLanguage, t]
  );

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
